# Change these first
owner: arisstadev
repo: upptime

sites:
  - name: AJTM Frontend
    url: https://ajtm.com.mx
  - name: AJTM Admin
    url: https://admin-beige-three.vercel.app
  - name: Arissta
    url: https://arissta.com
  - name: Loading Dock
    url: https://lloadingdock.com
  - name: MLM Minerales
    url: https://mlmeminerales.com
  - name: Team CLD
    url: https://teamcld.com
  - name: Thermo Ingeniería
    url: https://thermoingenieraylequipos.com

status-website:
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Arissta Monitor
  introTitle: "**Arissta** uptime monitor"
  introMessage: Sistema de monitoreo para todos los sitios web
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Telegram notifications
notifications:
  - type: telegram
    botToken: ${{ secrets.TELEGRAM_BOT_TOKEN }}
    chatId: ${{ secrets.TELEGRAM_CHAT_ID }}
